version: '3.7'

services:
  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nataha
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=user